### PR TITLE
Make Application testable

### PR DESCRIPTION
**Pull request by martenb**
We need to test our application, so we need to fake the incoming request.

### CODE REVIEW

**Comment by martenb** [comment]
I made workaround using Mockery, but it will be nicer, to have support by default

https://github.com/adbrosaci/controller-tester/commit/98c7d03be21c931cbd469ca67d9bcdf24efd7e82

**Comment by f3l1x** [comment]
Cool, thank you.

**Comment by martenb** [comment]
@f3l1x ?

**Comment by f3l1x** [comment]
https://github.com/contributte/middlewares/releases/tag/v0.11.1

I had to fix codesniffer + tests coverage.

**Comment by martenb** [comment]
Thanks

**Pull request merged**
